# Script for uploading LSIF to multiple files failing 



- **Zendesk Link:** [#3616](https://sourcegraph.zendesk.com/agent/tickets/3616)

- **CSE:** Jason Harris

- **Customer:** <!-- Redact if this contains personally identifying information --> Kryptos Logic


<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->

<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->



## Technical Environment

- **Version:** 3.31

- **Deployment:** Docker

- **External Services:**

- **Auth Providers:**





## Links
<!-- Data for CSE manual entry -->
- **Slack Links:** https://sourcegraph.slack.com/archives/C01HW836940/p1632945644259400

- **GitHub Issue Link:** N/A

- **Doc Update Link:** https://github.com/sourcegraph/snippets/pull/1



## Summary
### Description of Customer Issue:  

The customer was unable to upload LSIF to multiple files.



### Troubleshooting Steps:  

Tried doing the same on a test instance. I ran into the same issues. I also asked Ben to test, he also found the same issue.



### Resolution:  

Elevated to batch changes, who found that the script was broken. This was an issue with github expression syntax clashing with sourcegraph's own expression syntax, leaving the secrets object wasn't readable at runtime. We fixed the expression syntax from 



SRC_ACCESS_TOKEN: \${{secrets.srcAccessToken}}
SRC_ENDPOINT: \${{ secrets.srcEndpoint }}

to 

SRC_ACCESS_TOKEN: ${{ \\${{ secrets.srcAccessToken }} }}
SRC_ENDPOINT: ${{ \\${{ secrets.srcEndpoint }} }} 



This fixed the issue and allowed the customer to upload LSIF to multiple files.



### Relevant Error / Logs:  

<!-- Please redact keys, tokens, and personal identifying information -->

```2021-09-29T20:20:45.169366+01:00 stdout | 
2021-09-29T20:20:45.169416+01:00 stdout | 
2021-09-29T20:20:45.169618+01:00 stderr | /tmp/tmp.BD0cBfkWc2: line 26:     lsif-go:
2021-09-29T20:20:45.169662+01:00 stderr | 
2021-09-29T20:20:45.169682+01:00 stderr |         runs-on: ubuntu-latest
2021-09-29T20:20:45.169694+01:00 stderr | 
2021-09-29T20:20:45.169705+01:00 stderr |         container: sourcegraph/lsif-go
2021-09-29T20:20:45.169715+01:00 stderr | 
2021-09-29T20:20:45.169725+01:00 stderr |         steps:
2021-09-29T20:20:45.169735+01:00 stderr | 
2021-09-29T20:20:45.169755+01:00 stderr |             - uses: actions/checkout@v1
2021-09-29T20:20:45.169766+01:00 stderr | 
2021-09-29T20:20:45.169777+01:00 stderr |             - name: Generate LSIF data
2021-09-29T20:20:45.169787+01:00 stderr | 
2021-09-29T20:20:45.169797+01:00 stderr |               run: lsif-go
2021-09-29T20:20:45.169806+01:00 stderr | 
2021-09-29T20:20:45.169816+01:00 stderr |             - name: Upload LSIF data
2021-09-29T20:20:45.169826+01:00 stderr | 
2021-09-29T20:20:45.169835+01:00 stderr |               run: src lsif upload
2021-09-29T20:20:45.169845+01:00 stderr | 
2021-09-29T20:20:45.169855+01:00 stderr |               env:
2021-09-29T20:20:45.169864+01:00 stderr | 
2021-09-29T20:20:45.169878+01:00 stderr |                 SRC_ACCESS_TOKEN: ${{ secrets.srcAccessToken }}
2021-09-29T20:20:45.169887+01:00 stderr | 
2021-09-29T20:20:45.169897+01:00 stderr |                 SRC_ENDPOINT: ${{ secrets.srcEndpoint }}
2021-09-29T20:20:45.169907+01:00 stderr | 
2021-09-29T20:20:45.169918+01:00 stderr | 
2021-09-29T20:20:45.169932+01:00 stderr | 
2021-09-29T20:20:45.169944+01:00 stderr | : bad substitution
2021-09-29T20:20:45.169956+01:00 stderr | 
2021-09-29T20:20:45.324216+01:00 [Step 1] took 811ms; error running Docker container: exit status 1```
