
# repos not getting indexed / not getting synced / getting evicted <!-- Ticket Title  Hint: include keywords to make it searchable -->

- Zendesk Link: [#5390](https://sourcegraph.zendesk.com/agent/tickets/5390)
- Application engineer: Kelvin Lee
- Customer: Apple <!-- Redact if this contains personally identifying information -->
- Date: Jan 4

<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->
<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->

## Technical Environment
- Version: 3.32.0‚Äã
- Deployment: docker-container
- External Services: OTHER
- Auth Providers: saml


## Links
<!-- Data for application engineer manual entry -->
- Slack Links: [Slack](https://sourcegraph.slack.com/archives/C01NM1WFVH8/p1641408184019500)
- GitHub Issue Link: [GitHub RFH](https://github.com/sourcegraph/customer/issues/615), [Feature Request](https://github.com/sourcegraph/sourcegraph/issues/29588)
- Doc Update Link: None

## Summary
### Description of Customer Issue
Repo sync/index issues.

### Troubleshooting Steps
Most of these were red-herrings/non-useful: It eventually led to a feature request where our error logs were mis-reporting the symptoms/where our error logs were not that useful. But here goes anyways...:

Typical grab logs from gitserver, repoupdater, sourcegraph-frontend-*

Check for database corruption using [this](https://docs.sourcegraph.com/admin/migration/3_31#check-for-prior-index-corruption-before-upgrading) doc.

Eventually customer, at their own accord, deleted their whole instance and just started over üòì 

### Resolution
Customer discovered that it was a storage issue:

> After deleting instance, we found that, storage was the issue and sourcegraph errored with unable to connect to github rather than "insufficient space/memory error". We gave 200GB as storage for gitserver statefulset.

> Earlier it was 20GB and there was not enough space to download 1700 git repos.¬† With this can you reproduce this issue and make sure sourcegraph error logs for insufficient space. This helps you with other customers also.

> Which resulted in resolution of github connectivity error here


We ended up filing a [feature request](https://github.com/sourcegraph/sourcegraph/issues/29588) for a more accurate error log.

### Relevant Docs Pages Used/Created
https://docs.sourcegraph.com/admin/how-to/troubleshoot-pod-eviction#steps-to-troubleshoot

 

### Relevant Error / Logs
<!-- Please redact keys, tokens, and personal identifying information -->
"evicted" pods

gitserver: (didn't help much but was reported)
`‚ÄúSetting last error in DB‚Äù error=‚Äúsetting last error: unexpected EOF‚Äù`

gitserver: (didn't help much but was reported)
`t=2021-12-17T09:05:43+0000 lvl=eror msg="performing background repo update" error="failed to fetch: failed to update with output \"fatal: unable to access 'https://github.pie.apple.com/aos-aws/account-parameters/': The requested URL returned error: 504\\n\": exit status 128"`

gitserver: (didnt help much but was reported)
`t=2021-12-17T09:05:43+0000 lvl=eror msg="performing background repo update" error="failed to fetch: failed to update with output \"fatal: unable to access 'https://github.pie.apple.com/aos-uk-eng/durer/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.pie.apple.com:443 \\n\": exit status 128"`

github-proxy:
`t=2021-12-15T23:02:36+0000 lvl=eror msg="retrying HTTP request failed" attempt=20 method=POST url=http://sourcegraph-frontend-internal/.internal/configuration status=0 err="dial tcp 10.100.213.51:80: connect: connection refused"`

Weird hexadecimal adress logs:
`t=2022-01-06T22:04:12+0000 lvl=dbug msg="TRACE internal" host=sourcegraph-frontend-internal path=/.internal/configuration code=200 duration=2.844318ms
t=2022-01-06T22:04:18+0000 lvl=warn msg="Reset stalled record back to 'queued' state" name=repo_sync_worker_resetter id=8101 timeSinceLastHeartbeat=1m30.985767797s
panic: unreachable`

```
goroutine 695 [running]:
github.com/sourcegraph/sourcegraph/internal/repos.(*Syncer).sync(0xc0004fd880, {0x25fcf08, 0xc001b9ea80}, 0xc001b56fc0, 0xc0001a4f00)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:632 +0xfec
github.com/sourcegraph/sourcegraph/internal/repos.(*Syncer).SyncExternalService(0xc0004fd880, {0x25fcfb0, 0xc001b928d0}, 0xc001b7d7d0, 0x40d207)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:459 +0x725
github.com/sourcegraph/sourcegraph/internal/repos.(*syncHandler).Handle(0xc001717380, {0x25fcfb0, 0xc001b928d0}, {0x25ba7a0, 0xc001b665b0})
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:123 +0x7e
github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).handle(0xc0013fee00, {0x25fcf08, 0xc001b8e400}, {0x25ba7a0, 0xc001b665b0})
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:305 +0x1df
github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle.func2()
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:291 +0x91
created by github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:275 +0x429
```

^ This weird hexadecimal stuff was of interested/flagged as an investigation point, as shown [here](https://github.com/sourcegraph/customer/issues/615#issuecomment-1007010874), and elaborated on [here](https://github.com/sourcegraph/customer/issues/615#issuecomment-1007334732). 
 
!!! NOTE: Most of the error logs were red-herrings, but just recording here just in case it helps draw some comparisons to your case.

<!--¬†Once complete, upload a copy to https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets¬†as a .md file -->
<!-- Name the file 5390.md -->
