
# Re: [Sourcegraph] Re: Sourcegraph returning 500 issue; what we did to fix it <!-- Ticket Title  Hint: include keywords to make it searchable -->

- Zendesk Link: [#6147](https://sourcegraph.zendesk.com/agent/tickets/6147)
- Application engineer: Warren Gifford
- Customer: Brex <!-- Redact if this contains personally identifying information -->
- Date: Feb 9

<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->
<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->

## Technical Environment
- Version: ​
- Deployment:
- External Services:
- Auth Providers:


## Links
<!-- Data for application engineer manual entry -->
- Slack Links:
- GitHub Issue Link: https://github.com/sourcegraph/customer/issues/695
- Doc Update Link:

## Summary
### Description of Customer Issue

A customer-managed instance reported a repo that was not updating

### Troubleshooting Steps

Upon investigation, I found that the customers grafana charts were showing that the gitserver was underprovisioned

### Resolution

Allocating more mem to the gitserver reinitiated synching 

### Relevant Docs Pages Used/Created

### Relevant Error / Logs
<!-- Please redact keys, tokens, and personal identifying information -->
t=2022-02-10T00:37:03+0000 lvl=warn msg="runUpdateLoop: error updating repo" uri=github.com/brexhq/credit_card err="context deadline exceeded"
t=2022-02-10T01:48:58+0000 lvl=warn msg="runUpdateLoop: error updating repo" uri=github.com/brexhq/credit_card err="context deadline exceeded"
t=2022-02-10T03:13:00+0000 lvl=warn msg="runUpdateLoop: error updating repo" uri=github.com/brexhq/credit_card err="context deadline exceeded"
t=2022-02-10T05:00:15+0000 lvl=warn msg="runUpdateLoop: error updating repo" uri=github.com/brexhq/credit_card 



<!-- Once complete, upload a copy to https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets as a .md file -->
<!-- Name the file 6147.md -->
