
# repository does not exist / not cloned but also in UI but not in UI <!-- Ticket Title  Hint: include keywords to make it searchable -->

- Zendesk Link: [#7670](https://sourcegraph.zendesk.com/agent/tickets/7670)
- Application engineer: Kelvin Lee
- Customer: Capital One <!-- Redact if this contains personally identifying information -->
- Date: Apr 14

<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->
<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->

## Technical Environment
- Version: No telemetry
- Deployment: Uhhh, I think it's kubernetes? But they were redploying recently? Idk man
- External Services: GitHub... I think lol
- Auth Providers: ? Not sure


## Links
<!-- Data for application engineer manual entry -->
- Slack Links: Honestly kind of all over the place, but this ticket originates from [here](https://sourcegraph.slack.com/archives/C01QNMSLTFZ/p1649963254593959). Some messages within the channel. Also this [2nd](https://sourcegraph.slack.com/archives/C01QNMSLTFZ/p1650482182366479) thread.
- GitHub Issue Link:
- Doc Update Link:

## Summary
### Description of Customer Issue

As described by customer:

> Sourcegraph is telling me that some repositories are not cloned … when I go to clone them, it tells me repository does not exist … when I go to github the repository does exist and I have access to it … ?
>

Describing some of these repositories...:

> - repositories that are “disabled by administrator” in GitHub enterprise … basically the repository exists however it cannot be indexed … in this case … the error message seems to need improving
> - repositories that cannot be cloned but they do exist … in these cases I cannot even click the settings button because the UI is telling me the repo does not exist

### Troubleshooting Steps and Investigations

1. Looked at logs from `repo-updater`:

   ```
   t=2022-04-20T19:10:09+0000 lvl=warn msg=“runUpdateLoop: error updating repo” uri=<REDACTED> err=“error cloning repo: repo <REDACTED> not cloneable: exit status 128 (output follows)\n\nremote: Access to this repository has been disabled by your site administrator.\nremote: Please contact them to restore access to this repository.\nfatal: unable to access ‘REDACTED‘: The requested URL returned error: 403"
   t=2022-04-20T19:10:09+0000 lvl=warn msg=“runUpdateLoop: error updating repo” uri=<REDACTED> err=“error cloning repo: repo <REDACTED> not cloneable: exit status 128 (output follows)\n\nremote: Access to this repository has been disabled by your site administrator.\nremote: Please contact them to restore access to this repository.\nfatal: unable to access ‘REDACTED‘: The requested URL returned error: 403"
   ```

   Evaluation: 

   > Although `runUpdateLoop` had been mentioned in some \[past resolved tickets], I only see provisioning and certificate (auth stuff) issues being mentioned, and nothing about, say, corruptibility and disabled repos, as we had been thinking about. So it seems that runUpdateLoop is a pretty high-level, non-specific error message

   A better, next place to look is `gitserver`. But... customer did not end up responding with `gitserver` logs, unfortunately.

### Resolution
No answer/No firm resolution. Customer seems to have moved on from the issue.

The suspicions at the time were:

- the customer shared info about how some of the repos were "corrupted", apparently some sort of notion or quality that was specific to GitHub. Sourcegraph might not be detecting this "corruption". Not sure. One way to see if Sourcegraph does have observability of this "corruption" would have been to check `gitserver` logs.

### Relevant Docs Pages Used/Created
None

### Relevant Error / Logs
<!-- Please redact keys, tokens, and personal identifying information -->
Logs above already.

<!-- Once complete, upload a copy to https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets as a .md file -->
<!-- Name the file 7670.md -->
